paularmstrong/normalizr

README.md

feat: update readme examples to ES6

---

.gitignore
src/index.js
test/index.js

normalize method now takes a 3rd options param with only supported option being assignEntity
See issue #10

Add assignEntity via options param to normalize

---

README.md
src/ArraySchema.js
src/index.js
test/index.js

Allow polymorphic arrays

---

.travis.yml

Test on Node.js 0.10, 0.12 & 4.2 (LTS)

---

src/index.js
test/index.js

Fix key confliction with Object's prototype

---

README.md
src/index.js
test/index.js

Fixes #34.
@gaearon what do you think?

Custom `mergeIntoEntity`

---

README.md
src/EntitySchema.js
src/IterableSchema.js
src/index.js
test/index.js

I already created an issue (see #70) to discuss consistency between relations but people are asking me to create a PR, so here it is ! I tried being as complete as I could, there are tests and docs with it !
Should I squash everything ?

Consistent relations, see #70

---

src/EntitySchema.js
test/index.js

Reverts gaearon/normalizr#56 for the reasons highlighted here: https://github.com/gaearon/normalizr/pull/80#issuecomment-206963278

Revert "Schema.define could return associated instance"

---

index.d.ts
src/index.js
test/index.js

rebased https://github.com/paularmstrong/normalizr/pull/132 to master 
@paularmstrong

(feat) add ability to dynamically set nested schema type

---

README.md

The redux real world example link is out of date
Update example link

Update redux real world example link

---

README.md

Redux repo link is out of date
Update Redux link

Update Redux repo link

---

package.json

TypeScript cannot resolve module path while compiling. A recent change moved the location of index.js and index.d.ts and the entry point for index.js inside package.json. But updating the "typings" key in package.json was missed.
Fill in right path to typings

#178 index.d.ts is in the same directory as index.js

---

index.d.ts
package.json
src/__tests__/typescript.test.js
src/__tests__/typescript/array.ts
src/__tests__/typescript/array_schema.ts
src/__tests__/typescript/entity.ts
src/__tests__/typescript/github.ts
src/__tests__/typescript/object.ts
src/__tests__/typescript/relationships.ts
src/__tests__/typescript/union.ts
src/__tests__/typescript/values.ts

Typings for normalizr v3

---

docs/api.md

Incorrect `result` value in [api.md](https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#output).
Fix it.

Edit example output in a readme.

---

src/schemas/Polymorphic.js
src/schemas/__tests__/Union.test.js

https://github.com/paularmstrong/normalizr/issues/255
Explain the problem that this pull request aims to resolve.
Implemented
Explain your approach. Sometimes it helps to justify your approach against some others that you didn't choose to explain why yours is better.

Fixed denormalization using `schema.Union` with immutable data

---

docs/api.md

Doc is unclear what the return value of `idAttribute` function should be.
Closes #260 
Update the doc to clarify, also include an example.

DOC: Clarify Entity idAttribute behavior

---

.babelrc
package.json
rollup.config.js
src/schemas/__tests__/Entity.test.js
yarn.lock

No "module" entry. Having this allows bundlers to apply optimization techniques such as tree-shaking and scope hoisting.
I've updated several related deps and added a new output entry in rollup.config.js
If you have any questions why certain changes were made, please just ask and I will provide any necessary information.

Refactored build process, distributing module entry

---

.babelrc
.babelrc.js
package.json
rollup.config.js
yarn.lock

Follow up to https://github.com/paularmstrong/normalizr/pull/318#discussion_r166977224

Deduplicated babel config

---

README.md

docs(README): add install part

---

docs/api.md

The example of fallbackStrategy is broken and missing important part of code.
See the code.

fix example of fallbackStrategy
