paularmstrong/normalizr

ArraySchema.js, index.js, package.json
[lodash-node seems to be deprecated](https://github.com/lodash/lodash-node). This pull request updates the dependency to use lodash 3.0.0 instead.
=> Updates dependency from lodash-node 2.4.1 to lodash 3.0.0

src/EntitySchema.js, src/index.js, test/index.js
Hello!
I have ran into a few cases where a server -- not controlled by me -- returns nested JSON where:
* there isn't a single key which can serve as an identifier slug
* or the slug is embedded further within the object
* or the key requires some simple preprocessing
This PR uses the existing API of normalizr, but extend the `idAttribute` option to accept arbitrary functions. An example use case is in the included test.
=> Add ability to specify custom id attribute function

README.md, src/IterableSchema.js, src/UnionSchema.js, src/index.js, test/index.js
For collection fields `arrayOf` and `valuesOf` both allow polymorphic schemas if you specify a `schemaAttribute` option.  I didn't see the ability to do this for a non-collection field.  The use case for this is if a field can also be polymorphic.
Mentioned in issue : https://github.com/gaearon/normalizr/issues/40
An example would be a `group` where the owner could be a `group` or a `user`.
```js
var user = new Schema('users'),
group = new Schema('groups'),
owner = unionOf({
users: user,
groups: group
}, { schemaAttribute: 'type' });
group.define({
owner: owner,
});
```
This pull request adds the syntax `unionOf`.  It mimics the behavior found in `IterableSchema` but applies it in a non-iterable manner.
This could also pull the polymorphic logic out of `IterableSchema` by making …
=> unionOf -- extend polymorphic unions to fields

README.md, src/EntitySchema.js, test/index.js
This adds back the `getIdAttribute()` method that existed in [`v1.0.0`](https://github.com/gaearon/normalizr/blob/f3294e732bdf92820acba89f3a70eb8d5316a976/src/EntitySchema.js#L15-L17).
This is helpful for me when using with a library like `redux-crud` where it also needs the `idAttribute` passed in as an option. With this change I can create my schema as usual, and then read the idAttribute and pass it directly to the `redux-crud` reducer for each entity.
=> add back idAttribute method

package.json, src/IterableSchema.js, src/index.js, test/index.js
Pros:
* New! Shiny! Hot off the presses lodash v4.0.0
* Likely longer maintained
* Shorter require paths
Cons:
* Bundled size goes from ~4.3k min+gz to 5.6kgz. ¯\\\_(ツ)\_/¯
* Drops support for IE < 9, like upcoming React v0.15
Tests continue to pass. Thanks Dan!
=> Use Lodash v4 and shortened paths

src/index.js, test/index.js
When using `assignEntity`, we need to build values based on information from multiple keys/entities in the original input to `normalize`. 
Why do this here? When reading from a state happens more often than writing, it's much better to have this done once on receipt than every time it's accessed.
Change `assignEntity` to be given a fourth argument, the value of the original, non-normalized object.
Resolves #64
=> Give assignEntity access to the original input object

README.md
This concerns improving the Usage example to better show how the second parameter for normalize() is used. 
Currently, the example in the Usage section has these two normalize calls, which handle responses with similar structure:
```
response = normalize(response, {
articles: arrayOf(article)
});
response = normalize(response, {
users: arrayOf(user)
});
```
The example could be more informative, if it showed how to normalize two different response object structures, like this:
```
// response is just one article object
response = normalize(response, article);
// response is an object with a reference to an array of article objects
response = normalize(response, {
articles: arrayOf(article)
});
```
In addition to revising the Usage example, I suggest adding these examples to the …
=> Edit Usage and normalize() examples to explain second parameter better

src/index.js
The Array.isArray() checks included in the normalize function were not needed since lodash's isObject() already checks for valid arrays
```
_.isObject(value)
Checks if value is the language type of Object. 
(e.g. arrays, functions, objects, regexes, new Number(0), and new String(''))
```
[Source] (https://devdocs.io/lodash~4/index#isObject)
=> Remove unnecessary Array.isArray() checks

src/EntitySchema.js
Found myself expecting `Schema.define()` to return the Schema instance when doing:
```javascript
// In './Group.js'
import { arrayOf } from 'normalizr';
import User from './User';
export default new Schema('groups').define({
users: arrayOf(User)
});
```
Thought it'd be a good idea if it did return it.
=> Schema.define could return associated instance

README.md, src/EntitySchema.js, src/index.js, test/index.js
This PR is a small change to provide ```schema``` as an argument to the ```assignEntity``` function. 
My use-case is that when normalizing entities I want the key to be present under a different name in certain circumstances. I need to support both normalized and denormalized data and having fields with the same name but different types is causing quite a lot of confusion and noise.
With this change I can flag the schemas which I want to be assigned with a new name and then override the assignEntity method. See the added test for an example of this working.
Happy to discuss or make changes if you want, many thanks.
=> provide schema in assignEntity

README.md
Fixes a simple typo in the README in the section for `unionOf`.
=> README typofix`valueOf`=> `valuesOf`

index.d.ts
defaults attribute is not preset in SchemaOptions type
**Input**
```js
new Schema('data', {
idAttribute: 'ID',
defaults : { defaultValue: 1 }
});
```
**Output**
I'm getting following error from TypeScript
`Object literal may only specify known properties, and 'defaults' does not exist in type ...`
**Solution** 
Add `defaults?:any` to type script definition file on SchemaOptions type:
```js
export type SchemaOptions = {
idAttribute?: string | ExtractAttribute;
meta?: any;
assignEntity?: AssignEntity;
defaults?: any;
}
```
also add `getDefaults(): any;` to Schema class.
=> add defaults typings

README.md, src/EntitySchema.js, src/index.js, test/index.js
It is hard to deal with collections keyed by ID without an ID in the entity itself
Refactored #73 by to pass test. Allows `idAttribute` to be passed a `key` with which to normalize IDs on. Also fixed some instances where `collectionKey` wasn't being passed to `visit()`, and added documentation.
=> Can normalize entities keyed with their ID

docs/api.md
Typo in docs: missed coma
Fix this typo
=> fix typo in docs

index.d.ts, src/__tests__/typescript/entity.ts
Fixes #204.
According to the documentation the processStrategy method should return an object.
processStrategy(value, parent, key): Strategy to use when pre-processing the entity. Use this method to add extra data, defaults, and/or completely change the entity before normalization is complete. Defaults to returning a shallow copy of the input entity.
But in the index.d.ts the processStartegy is defined as a SchemaFunction which is a function that returns string.
Also in the relationship example, processStrategy returns an object.
When I try to use normalizr in Typescript, the processStrategy is expecting to return a string instead of a object.
Update the index.d.ts to change the SchemaFunction return from sting to any.
=> fix(index.d.ts): SchemaFunction return updated to any

docs/api.md, src/schemas/Polymorphic.js, src/schemas/__tests__/Array.test.js, src/schemas/__tests__/Union.test.js, src/schemas/__tests__/Values.test.js, src/schemas/__tests__/__snapshots__/Array.test.js.snap, src/schemas/__tests__/__snapshots__/Union.test.js.snap, src/schemas/__tests__/__snapshots__/Values.test.js.snap
Polymorphic mappings (Array, Union, Values) require strict schema definitions. This means that if your API returns something you didn't expect, Normalizr will throw an error.
Make it not strict and just retain the original input value in the result.
Fixes #207
=> Retain items in polymorphic mappings without defined schema

src/__tests__/__snapshots__/index.test.js.snap, src/__tests__/index.test.js, src/index.js, src/schemas/Array.js, src/schemas/Entity.js, src/schemas/Object.js, src/schemas/Polymorphic.js, src/schemas/Union.js, src/schemas/Values.js
`denormalize` method doesn't support [recursive linked entities](https://github.com/paularmstrong/normalizr/issues/216).
`__cache` key is added to `entities` object parameter for keeping already visited entities. The same approach is already used in [denormalizr](https://github.com/gpbl/denormalizr/commit/81df0765af65dbf19c85773e1f36978debf4f29e) package.
=> Added recursive dependencies support for denormalize method

docs/api.md, src/__tests__/index.test.js, src/schemas/Entity.js
`schema.Entity` should expose the `idAttribute` it gets in the constructor, like it did in v1.x & v2.x
Save `options.idAttribute` in `this._idAttribute`, expose this field with a getter called `idAttribute`.
=> Add `get idAttribute()` to schema.Entity

package.json, src/index.js, src/schemas/Entity.js, src/schemas/ImmutableUtils.js, src/schemas/Object.js, src/schemas/__tests__/Array.test.js, src/schemas/__tests__/Entity.test.js, src/schemas/__tests__/Object.test.js, src/schemas/__tests__/Union.test.js, src/schemas/__tests__/Values.test.js, src/schemas/__tests__/__snapshots__/Array.test.js.snap, src/schemas/__tests__/__snapshots__/Entity.test.js.snap, src/schemas/__tests__/__snapshots__/Object.test.js.snap, src/schemas/__tests__/__snapshots__/Union.test.js.snap, src/schemas/__tests__/__snapshots__/Values.test.js.snap, yarn.lock
Fixes #222 
First I want to say that I've been using and following this repo for quite a while and it's great to see `denormalize` finally land! 
It seems that most places I've seen that suggest using `normalizr` also suggest using an immutable store for entities. However, in doing so you lose the ability to use `denormalize`. Adding `immutable` as a dependency would add complexity and bloat for users who are not using immutable data.
Update `denormalize` to handle both mutable and immutable entities without actually requiring `immutable` as a dependency.
Support is handled by using simple `getIn`, `setIn`, `hasIn` methods that defer to the immutable implementations if the object is immutable otherwise implement the same behavior on plain javascript objects/arrays. `immutable-js` is …
=> Support denormalizing from immutable entities

src/index.js, src/schemas/Entity.js, src/schemas/__tests__/Entity.test.js, src/schemas/__tests__/__snapshots__/Entity.test.js.snap
Following from discussion here https://github.com/paularmstrong/normalizr/pull/228#discussion_r100351657
When an entity is not found during denormalization, it throws an unexpected exception.
```js
const mySchema = new schema.Entity('tacos');
const entities = {
tacos: {
1: { id: 1, type: 'foo' }
}
};
denormalize(3, mySchema, entities)
> TypeError: Cannot read property 'id' of undefined
at EntitySchema._getId (~/normalizr/dist/normalizr.js:226:65)
at EntitySchema.getId (~/normalizr/dist/normalizr.js:245:19)
at ~/normalizr/dist/normalizr.js:635:21
at EntitySchema.denormalize (~/normalizr/dist/normalizr.js:273:20)
at unvisit (~/normalizr/dist/normalizr.js:612:17)
at Object.denormalize$1 [as denormalize] (~/normalizr/dist/normalizr.js:651:10)
at repl:1:3
at realRunInThisContextScript …
```
=> Handle missing data in denormalize

docs/api.md, src/__tests__/__snapshots__/index.test.js.snap, src/__tests__/index.test.js, src/index.js
Recursive denormalization doesn't work as expected. If an entity is referenced by two separate entities (not in the same recursive tree), the second reference to the nested entity will not be denormalized properly (See #233)
Reverting the recursive handling for now.
=> Revert recursive denormalization

src/index.js, src/schemas/Array.js, src/schemas/Entity.js, src/schemas/ImmutableUtils.js, src/schemas/Object.js, src/schemas/Polymorphic.js, src/schemas/Union.js, src/schemas/Values.js, src/schemas/__tests__/Entity.test.js, src/schemas/__tests__/__snapshots__/Entity.test.js.snap
Fixes #216 - denormalization with circular/recursive entities. Would replace #238.
Turned `unvisit` into a factory function that returns a cache-aware version of the former unvisit. When `unvisiting` an entity, we first check if it's in the cache
Some other benefits:
- `Entity.denormalize` is simpler: given an entity object, denormalize it. Previously it would handle either an ID or an object, but this logic is moved up a level.
- Previously if you denormalized the same entity multiple times (e.g. array of books with the same author) the entities would not be referentially equal. This was due to how we were preventing mutating the entities in the store. With this PR, those entities will have the same object reference.
- No longer need to pass around `getDenormalizedEntities` through all …
=> Handle recursive relationships in denormalize

package.json, rollup.config.js, yarn.lock
I added a UMD build to the rollup config.
With multiple rollup targets, we can no longer pass a 'dest' into the
filesize plugin. I updated the filesize plugin version because 1.2's
default renderer shows the output path.
Multiple targets might be a good approach to minification also.
I can add that to this PR if you'd like.
=> Add UMD build

index.d.ts, src/__tests__/typescript/entity.ts, src/schemas/__tests__/Entity.test.js
`Entity.key` property is defined using getter (https://github.com/paularmstrong/normalizr/blob/master/src/schemas/Entity.js#L28), but in the definition there is a `key(): string` method (https://github.com/paularmstrong/normalizr/blob/master/index.d.ts#L20) which is wrong.
Fixed index.d.ts based on source code: https://github.com/paularmstrong/normalizr/blob/master/src/schemas/Entity.js#L28
=> fix(definitions): Fixed Entity#key definition for typescript

docs/api.md
Just a minor edit of the documentation. I got confused by the documentation of instance methods. I assumed key and idAttribute are actually methods. I think it's clearer to add a separate `Instance Attributes` sections
=> Documentation: Clarify instance attributes vs instance methods

src/__tests__/index.test.js, src/schemas/ImmutableUtils.js
I had exceptions when normalizing objects who don't inherit from Object.prototype.
This PR is related to #246 
Check if object has `hasOwnProperty` before calling it.
=> hasOwnProperty error

src/__tests__/index.test.js, src/index.js
Returning falsy input causes valid ids such as "" and 0 to be returned,
even if they could otherwise be properly denormalized. Loosening this
check to undefined will allow `null` to be processed, for example, but
that shouldn't be too much of an issue.
`denormalize` returns unprocessed `input` value when `input` is falsy. `0` and `""` are both falsy but are potentially valid inputs. See https://github.com/paularmstrong/normalizr/issues/278
Instead of checking for falsy values, check for undefined. When a normalization has no result, the value given as input will likely be undefined. Some cases that should be and were previously short circuited will  not be (e.g. `false`, `null`), but the value:cost ratio of handling those cases explicitly seems low.
(note: not sure documentation needs to …
=> denormalize: replace falsy input check with undefined input check

src/__tests__/__snapshots__/index.test.js.snap, src/__tests__/index.test.js, src/index.js
Denormalizing fails if `idAttribute` option of `EntitySchema` used as a function which uses `parent` or `key` parameters.
Consider this use case
```
const data = [
{ id: '1', guest: null, name: 'Esther' },
{ id: '2', guest: {guest_id: 1}, name: 'Tom' }
]
const guestSchema = new schema.Entity('guests', {}, {
idAttribute: (value, parent, key) => `${key}-${parent.id}-${value.guest_id}`
})
const patronsSchema = new schema.Entity('patrons', {
guest: guestSchema
})
const normalizedData = normalize(data, [patronsSchema])
const denormalizedData = denormalize(
normalizedData.result, 
[patronsSchema], 
normalizedData.entities
)
```
Expected `denormalizedData` to be equal to `data` but got error
`TypeError: Cannot read property 'id' of undefined`
`unvisitEntity` calls `schema.getId(entity);` which …
=> Use input as id for unvisitEntity in denormalize

index.d.ts
With typescript, the normalize object lose his type
Generic function
=> Improve typescript typing

src/schemas/Object.js, src/schemas/__tests__/Object.test.js, src/schemas/__tests__/__snapshots__/Object.test.js.snap
Currently, if one has an `Object` schema that contains properties that are mapped to other entities, if the id of one of those mapped entities is `0` or some other falsy value, it will be skipped during denormalization. Seeing that `0` is not an uncommonly used id, it makes sense to allow non-null/non-undefined falsy values to be evaluated rather than skip them as if they were null or undefined.
Here is an example schema that would not currently allow a `categoryOwner` with an id of `0` to be denormalized, instead, denormalization of `categoryOwner` would be skipped and the value of `categoryOwner` would remain `0`:
```js
const userSchema = new schema.Entity('users');
const otherSchema = new schema.Entity('others', {
categoryInfo: {
categoryOwner: userSchema
}
});
```
The solution here …
=> Fixed denormalization skipping of falsy valued ids used in `Object` schemas

src/__tests__/__snapshots__/index.test.js.snap, src/__tests__/index.test.js, src/index.js, src/schemas/Array.js, src/schemas/Entity.js, src/schemas/Object.js, src/schemas/Polymorphic.js, src/schemas/Union.js, src/schemas/Values.js
Unable to normalize inputs with circular references. I get a `maximum call stack size exceeded` error.
This PR is based on https://github.com/paularmstrong/normalizr/pull/330 with a few changes (based on the fixes recommended there):
- Used `Array.prototype.some` for equality check instead of `Set` to avoid a polyfill
- Added tests using `toMatchSnapshot`
=> Add support for circular references

docs/api.md, index.d.ts
Fixes https://github.com/paularmstrong/normalizr/issues/364
Simple one liner
=> Allow symbol for Entity key

index.d.ts
It's very hard to infer anything about the types without generics. Given that it's most useful to have types for the data stored in your normalized cache this seems pretty essential.
The idea here is at some point you'll point to an entity whose processStrategy will return the type you expect.
Splitting the Schema union type was essential to distinguish between list results and singular results as well.
In the end I was able to create my own type in userland that could extract what type to expect:
```typescript
export type SchemaOf<T> = T extends SchemaArray<infer R>
? R[]
: T extends SchemaBase<infer R>
? R
: never;
```
=> [minor] Improve typescript types with generics

src/index.js, src/schemas/Entity.js
The support for circular references added with #335 comes with a significant performance cost.
For every entity the list of already parsed entities is searched. This leads to non-linear performance characteristics.
I’ve partitioned the visited entities lookup by ids. Entities with a different type that share the same id will still be added to a list, which shouldn't be a problem in practice. Using a Set would have been simpler, but that was ruled out [earlier](https://github.com/paularmstrong/normalizr/pull/330#discussion_r179919159).
```
const mySchema = new schema.Entity('tacos');
const data = [];
for (let i = 0; i < N; i++) {
data.push({ id: i, type: `foo-${i}` });
}
normalize(data, [mySchema]);
```
|N = 10,000 entities   |  |  |  |  |          |
| -------- | ---:| ---:| ---:| ---:| …
=> Improve performance of circular reference detection

src/__tests__/index.test.js, src/index.js
In Javascript typeof null === 'object'. 
Since the check in normalize includes one for !input, it should say 'found null' when null is passed rather than a confusing message that it found object when it needed object.
=> [fix] When normalize() receives null input, don't say it is an object

src/schemas/Polymorphic.js, src/schemas/__tests__/Array.test.js, src/schemas/__tests__/__snapshots__/Array.test.js.snap
Denormalization does not seem to produce the correct result when a singular Array schema owns an Object schema whose instances own an `id` property. 
For example:
```javascript
const cats = new schema.Entity('cats');
// catRecord instances own an `id` property
const catRecord = new schema.Object({
cat: cats
});
const catList = new schema.Array(catRecord);
```
The problem is in the the `denormalizeValue` method of the `Polymorphic` class.
When the value to be unvisited owns a property named `id`, then this method uses the value of the `id` property as the input value for the call to `unvisit` in place of the value itself, which is not the case on singular Array schema, where the value itself should always be used instead.
I've added a guard which prevents the value of the `id` property to …
=> fix(schemas): don't use schema to attribute mapping on singular array schemas

index.d.ts, src/__tests__/__snapshots__/index.test.js.snap, src/__tests__/index.test.js, src/schemas/Entity.js, src/schemas/Object.js, typescript-tests/object.ts
Reinstates https://github.com/paularmstrong/normalizr/pull/159, which [was unfortunately lost when v3 was released](https://github.com/paularmstrong/normalizr/issues/130#issuecomment-285012859).
Fixes https://github.com/paularmstrong/normalizr/issues/413
Related: https://github.com/paularmstrong/normalizr/issues/130
I will update documentation once the code side of things has been approved.
/cc @paularmstrong @jgutta @fxck @joewestcott
=> Add ability to dynamically set nested schema type

index.d.ts
When there are no items found for a particular entity, normalizr returns nothing for that entity.
The problem is that the TypeScript definitions expect there to always be an object, so TypeScript fails to catch issues which later appear at runtime as `undefined` type errors.
Normalizr's behavior in this area has been discussed here before: https://github.com/paularmstrong/normalizr/issues/290 
This PR doesn't change that, it just updates the TypeScript definition to match what Normalizr already returns.
Only issue is TypeScript will warn existing users about this error. It highlights a real potential bug in their system that it wasn't able to spot before, but likely to need users to fix their use of the result.entities object (or set `{}` as a default for undefined entities).
=> fix(typescript): entities undefined if none found

docs/api.md, src/index.js, src/schemas/Entity.js, src/schemas/__tests__/Entity.test.js
In some cases I would like to denormalize a structure with a list of Ids instead of a list of subobjects (reasons could be to limit fetched data). When i normalize this structure the normalization works, I am left with the entity ids, but there is no way to create stubs for the entities itself, which I find ok since there could be an instance of the same object somewhere else in the structure.
But when denormalizing this I will get back an array with undefined items. 
A possible solution to this could be to add a possibility to add a fallbackStrategy option to the EntitySchema where we could write our own fallback method for denormalization.
=> added a fallback strategy for denormalization

index.d.ts, typescript-tests/entity.ts
3.6.0 release introduces `fallbackStrategy` method, which is not usable with typescript, because of missing types
Add missing types
I also noticed that while prettier is installed in this project, it wasn't used on every file, I did that initially and the diff was much larger, which is out of scope of this particular PR, but I could do that separately  if you'd like.
=> Add types for fallback strategy
